#!/bin/zsh

echo "Running software update. If your device restarts, run setup again"

sudo softwareupdate -i -a --restart

echo "Running software update. If your device restarts, run setup again"

export SETUP_DIR=$0:A:h

mkdir -p /usr/local/share/zsh/site-functions
chmod 755 /usr/local/share/zsh
chmod 755 /usr/local/share/zsh/site-functions

#oh-my-zsh
sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"


# Homebrew
if ! type "brew" > /dev/null; then
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
fi

. $SETUP_DIR/source.zsh

$SETUP_DIR/init/directories.zsh
$SETUP_DIR/init/theme.zsh
source $SETUP_DIR/helpers.zsh

SOURCE_LINES='export DOTFILES_SOURCED=true
export DOTFILE_DIR="$HOME/dotfiles";
[ -s "$DOTFILE_DIR/source.zsh" ] && \. "$DOTFILE_DIR/source.zsh"
'

if [[ $(find_text 'DOTFILES_SOURCED' ~/.zshrc) ]]
then
    echo "Looks like dotfiles are already installed in ~/.zshrc, not adding the following lines"
    echo $SOURCE_LINES
else
    echo "Adding source line to ~/.zshrc"
    if ! [[ ( -f ~/.zshrc.predotfiles.bak ) ]]
    then
        echo "Backing up ~/.zshrc to ~/.zshrc.predotfiles.bak"
        cp ~/.zshrc ~/.zshrc.predotfiles.bak
    fi
    echo $SOURCE_LINES >> ~/.zshrc
fi

$SETUP_DIR/install.zsh
$SETUP_DIR/osx-preferences.sh